backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "courses"
    label: "Courses"
    folder: "assets/data"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "WhatsApp Link", name: "whatsapp", widget: "string" }